SERVJSP/EXAM_Phone/src/entity/Phone.java
package entity;

import javax.persistence.*;
import java.util.Objects;

@Entity
@Cacheable(value = false)
public class Phone {
    private int id;
    private String name;
    private String brand;
    private Float price;
    private String description;

    public Phone() {

    }

    public Phone(String name, String brand, float price, String description) {
        this.name = name;
        this.brand = brand;
        this.price = price;
        this.description = description;
    }

    @Id
    @Column(name = "id", nullable = false)
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Basic
    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Basic
    @Column(name = "brand", nullable = false, length = 10)
    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    @Basic
    @Column(name = "price", nullable = true, precision = 0)
    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    @Basic
    @Column(name = "description", nullable = true, length = 500)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Phone phone = (Phone) o;
        return id == phone.id &&
                Objects.equals(name, phone.name) &&
                Objects.equals(brand, phone.brand) &&
                Objects.equals(price, phone.price) &&
                Objects.equals(description, phone.description);
    }

    @Override
    public int hashCode() {

        return Objects.hash(id, name, brand, price, description);
    }
}

SERVJSP/EXAM_Phone/src/model/PhoneBean.java
package model;

import DA.PhoneDAO;
import entity.Phone;

import java.io.Serializable;
import java.util.List;

public class PhoneBean implements Serializable {
    private Phone phone;
    private PhoneDAO dao;

    public PhoneBean(){
        dao = new PhoneDAO();
    }

    public Phone getPhone() {
        return phone;
    }

    public void setPhone(Phone phone) {
        this.phone = phone;
    }

    public boolean addPhone() {
        return dao.createPhone(phone);
    }

    public List<Phone> getPhoneList() {
        return dao.getPhones();
    }
}

SERVJSP/EXAM_Phone/src/controller/PhoneServlet.java
package controller;

import entity.Phone;
import model.PhoneBean;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

public class PhoneServlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String name = request.getParameter("name");
        String brand = request.getParameter("brand");
        float price = Float.parseFloat(request.getParameter("price"));
        String description = request.getParameter("description");

        Phone phone = new Phone(name, brand, price, description);
        PhoneBean bean = new PhoneBean();
        bean.setPhone(phone);

        boolean result = bean.addPhone();
        request.getRequestDispatcher("listphone.jsp").forward(request, response);
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.getRequestDispatcher("listphone.jsp").forward(request, response);
    }
}

SERVJSP/EXAM_Phone/web/addphone.jsp
<%--
  Created by IntelliJ IDEA.
  User: bak
  Date: 18/06/2018
  Time: 14:46
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Add phone</title>
</head>
<body>
    <form action="phone" method="post">
        Name : <input type="text" name="name" required maxlength="50"><br>
        Brand :
        <select name="brand" id="brand" required>
            <option value="Apple">Apple</option>
            <option value="Samsung">Samsung</option>1
            <option value="Nokia">Nokia</option>
            <option value="Others">Other</option>
        </select><br>
        Price : <input type="number" name="price" step="0.01" required><br>
        Description : <textarea name="description" id="description" cols="30" rows="4" maxlength="500"></textarea><br>

        <input type="reset">
        <input type="submit" value="Add Phone">
    </form>
</body>
</html>

SERVJSP/EXAM_Phone/web/listphone.jsp
<%--
  Created by IntelliJ IDEA.
  User: bak
  Date: 18/06/2018
  Time: 14:46
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>List phone</title>
</head>
<body>
    <jsp:useBean id="bean" class="model.PhoneBean" scope="request"/>

    <a href="addphone.jsp">Add phone</a>

    <table border="1">
        <thead>
            <tr>
                <th>Name</th>
                <th>Brand</th>
                <th>Price</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <c:forEach items="${bean.phoneList}" var="phone">
                <tr>
                    <td>${phone.name}</td>
                    <td>${phone.brand}</td>
                    <td>${phone.price}</td>
                    <td>${phone.description}</td>
                </tr>
            </c:forEach>
        </tbody>
    </table>
</body>
</html>